# Generated by Django 5.1.2 on 2024-10-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('input', 'Input File'), ('optab', 'Optab File')], max_length=10),
        ),
    ]
