# Generated by Django 5.1.2 on 2024-10-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembler', '0002_remove_uploadedfile_uploaded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assembler_files/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(choices=[('input', 'Input'), ('optab', 'Optab')], max_length=50)),
                ('pass_number', models.PositiveSmallIntegerField(choices=[(1, 'Pass 1'), (2, 'Pass 2')])),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
