# Generated by Django 5.1.2 on 2024-11-02 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembler', '0003_assemblerfile_delete_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblerfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='assemblerfile',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='assemblerfile',
            name='pass_number',
        ),
        migrations.AddField(
            model_name='assemblerfile',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='assembler_inputs/'),
        ),
        migrations.AddField(
            model_name='assemblerfile',
            name='optab_file',
            field=models.FileField(blank=True, null=True, upload_to='assembler_optabs/'),
        ),
        migrations.AlterField(
            model_name='assemblerfile',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
